"""empty message

Revision ID: c3f32ba4a4ac
Revises: e14bd2db89bb
Create Date: 2017-04-27 23:11:07.931579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3f32ba4a4ac'
down_revision = 'e14bd2db89bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('role', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###
